projects:
  - title: Juego De La Vida
    slug: game-of-life
    url: proyectos.dehector.com/game-of-life
    description: El "Juego de la vida" de John Horton Conway. Un juego para cero jugadores. Ahora en tu navegador
    image_url: game-of-life.png
    image_alt: Juego De La Vida
    github_repo: hectorfranc.github.io

home:
  title: Inicio

static_sites:
  - slug: "404"
    description: 404 Page
    filename_with_ext: 404.html

content_path: /home/hector/Desktop/projects/hectorfranc.github.io/content/
templates_path: /home/hector/Desktop/projects/hectorfranc.github.io/templates
media_path: /home/hector/Desktop/projects/hectorfranc.github.io/media